In [14]:
import numpy as np

#from numpy import *

In [15]:
arreglo=np.array([[1,2,3],[4,5,6]])
print(arreglo)

[[1 2 3]
 [4 5 6]]


In [16]:
#Attibutos de NdArray
print("No. dimensiones",arreglo.ndim)
print("No. de elementos",arreglo.size)
print("No. de elementos de cada dimension",arreglo.shape)

No. dimensiones 2
No. de elementos 6
No. de elementos de cada dimension (2, 3)


In [17]:
#Arange y lindspace
vector_ara=np.arange(2,30,4)
print("Arange",vector_ara)

vector_lin=np.linspace(2,30,4)
print("Lindspace",vector_lin)

Arange [ 2  6 10 14 18 22 26]
Lindspace [ 2.         11.33333333 20.66666667 30.        ]


In [18]:
#Indexación

vector=np.arange(1,11)
vector

print("Vec. completo",vector[:])
print("Vec. ultimo elemento",vector[-1])
print("Vec. todos menos el ultimo",vector[:-1])
print("Rango", vector[2:-2])
print("Rango con paso",vector[2:-2:2])
print("Vec. invertido",vector[::-1])

Vec. completo [ 1  2  3  4  5  6  7  8  9 10]
Vec. ultimo elemento 10
Vec. todos menos el ultimo [1 2 3 4 5 6 7 8 9]
Rango [3 4 5 6 7 8]
Rango con paso [3 5 7]
Vec. invertido [10  9  8  7  6  5  4  3  2  1]


In [19]:
#Aleaotorio 

#vector_aleatorio=np.random.randint(50,size=(2,2))
vec_alea=np.random.randint(50,size=5)
vec_alea

array([21,  3, 17, 37,  9])

In [20]:
#Funciones importantes

print("Elemento mayor",vec_alea.max())
print("Elemento menor",vec_alea.min())
print("DesEstan",vec_alea.std())
print("Suma total",vec_alea.sum())

print("Indice de elemento mayor",np.argmax(vec_alea))
print("Indice de elemento menor",np.argmin(vec_alea))
print("Ordena",np.sort(vec_alea))

Elemento mayor 37
Elemento menor 3
DesEstan 11.62067123706716
Suma total 87
Indice de elemento mayor 3
Indice de elemento menor 1
Ordena [ 3  9 17 21 37]


In [21]:
#Operadores
v1=np.array([1,2,3])
v2=np.array([1,1,1])

print("Suma",v1+v2)
print("Producto uno a uno",v1*v2)
print("Producto punto",v1@v2)
print("Producto escalar", v1*5)
print("Producto cruz",np.cross(v1,v2))

Suma [2 3 4]
Producto uno a uno [1 2 3]
Producto punto 6
Producto escalar [ 5 10 15]
Producto cruz [-1  2 -1]


In [22]:
#Matrices
mtrx_alea=np.random.randint(50,size=(3,3))
mtrx_alea


array([[49,  3, 19],
       [ 3, 44, 27],
       [22, 42, 29]])

In [23]:
print("Renglon 2",mtrx_alea[2])
print("Columna 2",mtrx_alea[:,2])
print("Accediendo a ",mtrx_alea[2][2])
print("Accediendo a ",mtrx_alea[1,2])

renglon=[0,1]
columna=[0,2]

print("Accediendo a ",mtrx_alea[renglon,columna])

Renglon 2 [22 42 29]
Columna 2 [19 27 29]
Accediendo a  29
Accediendo a  27
Accediendo a  [49 27]


In [24]:
#===========P A N D A S================

In [25]:
import pandas as pd

In [26]:
s1=pd.Series([1,2,3,4,5,6,7,8,9])
print(s1)
print("Valores",s1.values)
print("Index",s1.index)

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int64
Valores [1 2 3 4 5 6 7 8 9]
Index RangeIndex(start=0, stop=9, step=1)


In [27]:
s2=pd.Series([1,2,3,4],index=["a","b","c","d"])
s2

a    1
b    2
c    3
d    4
dtype: int64

In [28]:
####OPERACIONES BASICAS
#s1[s1*2]
#s1*2

# Cuando se usa "in" se pregunta si existe el elemento en el index
"a" in s2

True

In [29]:
#DICCIONARIOS

prebes={"Prebe1":10,"Prebe2":8,"Prebe3":0,"Prebe4":6}
s_diccionarios=pd.Series(prebes)
s_diccionarios

Prebe1    10
Prebe2     8
Prebe3     0
Prebe4     6
dtype: int64

In [30]:
prebes={"Prebe1":1,"Prebe2":1,"Prebe3":0,"Prebe4":1}
s_diccionarios2=pd.Series(prebes)
s_diccionarios2

Prebe1    1
Prebe2    1
Prebe3    0
Prebe4    1
dtype: int64

In [31]:
s_diccionarios+s_diccionarios2

Prebe1    11
Prebe2     9
Prebe3     0
Prebe4     7
dtype: int64

In [32]:
s_diccionarios.name="Lista"
s_diccionarios.index.name="PREBES"

s_diccionarios

PREBES
Prebe1    10
Prebe2     8
Prebe3     0
Prebe4     6
Name: Lista, dtype: int64

In [33]:
#====================DATA FRAMES=======================

In [34]:
datos = {'Paises': ['Ecuador','Colombia','Chile','Peru','Paraguay','Bolivia','Brazil','Argentina','Uruguay'],
'Codigo': ['ECU','COL','CHL','PER','PRY','BOL','BRA','ARG','URY'],
'GINI': [44.7,49.7,46.6,43.3,48.8,44,53.3,41.2,39.5]} 


df=pd.DataFrame(datos)
df

Paises Codigo  GINI
0    Ecuador    ECU  44.7
1   Colombia    COL  49.7
2      Chile    CHL  46.6
3       Peru    PER  43.3
4   Paraguay    PRY  48.8
5    Bolivia    BOL  44.0
6     Brazil    BRA  53.3
7  Argentina    ARG  41.2
8    Uruguay    URY  39.5

#### Funciones basicas


In [35]:
#Imprime los primeros 5
df.head()

Paises Codigo  GINI
0   Ecuador    ECU  44.7
1  Colombia    COL  49.7
2     Chile    CHL  46.6
3      Peru    PER  43.3
4  Paraguay    PRY  48.8

In [36]:
#Imprime los ultimos con y sin argumentos
df.tail()

Paises Codigo  GINI
4   Paraguay    PRY  48.8
5    Bolivia    BOL  44.0
6     Brazil    BRA  53.3
7  Argentina    ARG  41.2
8    Uruguay    URY  39.5

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Paises  9 non-null      object 
 1   Codigo  9 non-null      object 
 2   GINI    9 non-null      float64
dtypes: float64(1), object(2)
memory usage: 344.0+ bytes


In [38]:
df.describe()

GINI
count   9.000000
mean   45.677778
std     4.366285
min    39.500000
25%    43.300000
50%    44.700000
75%    48.800000
max    53.300000

In [39]:
print("No. de registros: {}\n".format(len(df)))
print("Columnas del dataframe: {}\n".format(df.columns))
print("Numero de columnas del dataframe: {}\n".format(len(df.columns)))
print("dtype:\n{}\n".format(df.dtypes))
print("ndim: {}\n".format(df.size))
print("shape: {}\n".format(df.shape))
print("values: {}\n".format(df.values))
print("index: {}\n".format(df.index))

No. de registros: 9

Columnas del dataframe: Index(['Paises', 'Codigo', 'GINI'], dtype='object')

Numero de columnas del dataframe: 3

dtype:
Paises     object
Codigo     object
GINI      float64
dtype: object

ndim: 27

shape: (9, 3)

values: [['Ecuador' 'ECU' 44.7]
 ['Colombia' 'COL' 49.7]
 ['Chile' 'CHL' 46.6]
 ['Peru' 'PER' 43.3]
 ['Paraguay' 'PRY' 48.8]
 ['Bolivia' 'BOL' 44.0]
 ['Brazil' 'BRA' 53.3]
 ['Argentina' 'ARG' 41.2]
 ['Uruguay' 'URY' 39.5]]

index: RangeIndex(start=0, stop=9, step=1)



In [40]:
#============ ACCEDER A ELEMENTOS============

In [41]:
#Columna
paises=df["Paises"]
paises

paises=df.Paises
paises

0      Ecuador
1     Colombia
2        Chile
3         Peru
4     Paraguay
5      Bolivia
6       Brazil
7    Argentina
8      Uruguay
Name: Paises, dtype: object

In [42]:
#Dos columnas
pais_gini=df[["Paises","GINI"]]
print(pais_gini)

print("\n",df.Paises)

#Indexacion RENGLONES
pa=df[:2]
pa


      Paises  GINI
0    Ecuador  44.7
1   Colombia  49.7
2      Chile  46.6
3       Peru  43.3
4   Paraguay  48.8
5    Bolivia  44.0
6     Brazil  53.3
7  Argentina  41.2
8    Uruguay  39.5

 0      Ecuador
1     Colombia
2        Chile
3         Peru
4     Paraguay
5      Bolivia
6       Brazil
7    Argentina
8      Uruguay
Name: Paises, dtype: object


Paises Codigo  GINI
0   Ecuador    ECU  44.7
1  Colombia    COL  49.7

In [43]:
df2=pd.DataFrame(datos,columns=["Codigo","Paises","GINI"],index=(np.arange(1,10)))
df2

Codigo     Paises  GINI
1    ECU    Ecuador  44.7
2    COL   Colombia  49.7
3    CHL      Chile  46.6
4    PER       Peru  43.3
5    PRY   Paraguay  48.8
6    BOL    Bolivia  44.0
7    BRA     Brazil  53.3
8    ARG  Argentina  41.2
9    URY    Uruguay  39.5

In [44]:

##LOC (etiqueta)
ren_loc= df2.loc[1, "Paises"]
ren_loc
#"Ecuador"

consulta_loc=df2.loc[:2,["Codigo","Paises"]]
consulta_loc

Codigo    Paises
1    ECU   Ecuador
2    COL  Colombia

In [45]:
##ILOC
ren_loc= df2.iloc[1,1]
ren_loc #"Colombia"

consulta_iloc=df2.iloc[:2,:2]
consulta_iloc

Codigo    Paises
1    ECU   Ecuador
2    COL  Colombia

In [46]:
##MODIFICAR VALORES

In [47]:
df_original=df.copy()

In [48]:
df.loc[df.GINI<45,"GINI"]=0
df

Paises Codigo  GINI
0    Ecuador    ECU   0.0
1   Colombia    COL  49.7
2      Chile    CHL  46.6
3       Peru    PER   0.0
4   Paraguay    PRY  48.8
5    Bolivia    BOL   0.0
6     Brazil    BRA  53.3
7  Argentina    ARG   0.0
8    Uruguay    URY   0.0

In [49]:
df["GINI2"]=df.GINI/100
df

Paises Codigo  GINI  GINI2
0    Ecuador    ECU   0.0  0.000
1   Colombia    COL  49.7  0.497
2      Chile    CHL  46.6  0.466
3       Peru    PER   0.0  0.000
4   Paraguay    PRY  48.8  0.488
5    Bolivia    BOL   0.0  0.000
6     Brazil    BRA  53.3  0.533
7  Argentina    ARG   0.0  0.000
8    Uruguay    URY   0.0  0.000

In [50]:
## Funciones

In [51]:
print("Media:\n", df.mean())
print("\nMaximo:\n", df.max())
print("\nMaximo:\n", df.min())

Media:
 GINI     22.044444
GINI2     0.220444
dtype: float64

Maximo:
 Paises    Uruguay
Codigo        URY
GINI         53.3
GINI2       0.533
dtype: object

Maximo:
 Paises    Argentina
Codigo          ARG
GINI              0
GINI2             0
dtype: object


In [52]:
#ordenadoPorNombreLugar = data.sort_values('State', ascending=True)
#print(ordenadoPorNombreLugar.head())

OrdenadoPais=df.sort_values("Paises")
OrdenadoPais

Paises Codigo  GINI  GINI2
7  Argentina    ARG   0.0  0.000
5    Bolivia    BOL   0.0  0.000
6     Brazil    BRA  53.3  0.533
2      Chile    CHL  46.6  0.466
1   Colombia    COL  49.7  0.497
0    Ecuador    ECU   0.0  0.000
4   Paraguay    PRY  48.8  0.488
3       Peru    PER   0.0  0.000
8    Uruguay    URY   0.0  0.000

In [53]:
#https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv
    

In [54]:
info = pd.read_csv('https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv', sep = "\t")
print('tipo info: ',type(info))
info

tipo info:  <class 'pandas.core.frame.DataFrame'>


order_id  quantity                              item_name  \
0            1         1           Chips and Fresh Tomato Salsa   
1            1         1                                   Izze   
2            1         1                       Nantucket Nectar   
3            1         1  Chips and Tomatillo-Green Chili Salsa   
4            2         2                           Chicken Bowl   
...        ...       ...                                    ...   
4617      1833         1                          Steak Burrito   
4618      1833         1                          Steak Burrito   
4619      1834         1                     Chicken Salad Bowl   
4620      1834         1                     Chicken Salad Bowl   
4621      1834         1                     Chicken Salad Bowl   

                                     choice_description item_price  
0                                                   NaN     $2.39   
1                                          [Clementine]     $3.39   
2                                               [Apple]     $3.39   
3                                                   NaN     $2.39   
4     [Tomatillo-Red Chili Salsa (Hot), [Black Beans...    $16.98   
...                                                 ...        ...  
4617  [Fresh Tomato Salsa, [Rice, Black Beans, Sour ...    $11.75   
4618  [Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...    $11.75   
4619  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...    $11.25   
4620  [Fresh Tomato Salsa, [Fajita Vegetables, Lettu...     $8.75   
4621  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...     $8.75   

[4622 rows x 5 columns]

In [55]:
path="C:/Users/chilp/Desktop/PROTECO/INTERS/PYTHON/Avanzado/archivo_csv"
datos_csv=pd.read_csv(path,sep=",")
datos_csv.head()

QuotaAmount   StartDate        OwnerName  \
0       150000  2016-01-01      Chris Riley   
1       150000  2016-02-01      Chris Riley   
2       150000  2016-03-01      Chris Riley   
3       150000  2016-01-01  Harold Campbell   
4       150000  2016-02-01  Harold Campbell   

                               Username  
0   trailhead9.ub20k5i9t8ou@example.com  
1   trailhead9.ub20k5i9t8ou@example.com  
2   trailhead9.ub20k5i9t8ou@example.com  
3  trailhead14.jibpbwvuy67t@example.com  
4  trailhead14.jibpbwvuy67t@example.com

In [56]:
datos_csv.describe()
datos_csv.tail()

QuotaAmount   StartDate      OwnerName  \
13       150000  2016-02-01  Kelly Frazier   
14       150000  2016-03-01  Kelly Frazier   
15       150000  2016-01-01  Dennis Howard   
16       150000  2016-02-01  Dennis Howard   
17       150000  2016-03-01  Dennis Howard   

                               Username  
13  trailhead7.zdcsy4ax10mr@example.com  
14  trailhead7.zdcsy4ax10mr@example.com  
15  trailhead4.wfokpckfroxp@example.com  
16  trailhead4.wfokpckfroxp@example.com  
17  trailhead4.wfokpckfroxp@example.com

In [57]:
path="C:/Users/chilp/Desktop/PROTECO/INTERS/PYTHON/Avanzado/Sucursal.csv"
datos_Sucursal=pd.read_csv(path,sep=",")
datos_Sucursal.head()

AÑO     MES  SUCURSAL TIPO INGRESO    IMPORTE
0  2009   Agosto   México      Cheques   $543.00 
1  2010    Enero   México     Efectivo   $587.00 
2  2010  Febrero   México     Efectivo   $988.00 
3  2011    Marzo   México     Efectivo   $891.00 
4  2009    Abril   México     Depósito   $514.00

In [58]:
df

Paises Codigo  GINI  GINI2
0    Ecuador    ECU   0.0  0.000
1   Colombia    COL  49.7  0.497
2      Chile    CHL  46.6  0.466
3       Peru    PER   0.0  0.000
4   Paraguay    PRY  48.8  0.488
5    Bolivia    BOL   0.0  0.000
6     Brazil    BRA  53.3  0.533
7  Argentina    ARG   0.0  0.000
8    Uruguay    URY   0.0  0.000

In [59]:
#ASI SE CAMBIAN LOS NOMBRES DE LAS COLUMNAS

df.rename(columns={'GINI':'CalPrebe'})

Paises Codigo  CalPrebe  GINI2
0    Ecuador    ECU       0.0  0.000
1   Colombia    COL      49.7  0.497
2      Chile    CHL      46.6  0.466
3       Peru    PER       0.0  0.000
4   Paraguay    PRY      48.8  0.488
5    Bolivia    BOL       0.0  0.000
6     Brazil    BRA      53.3  0.533
7  Argentina    ARG       0.0  0.000
8    Uruguay    URY       0.0  0.000